### ISSUE TITLE
Adopt a consistent code style

### ISSUE THREAD

**Issue by bbatsov** [opal/opal#989]
Hey everyone,

Lately I've been browsing the source of the project to get some familiarity with it and I'm constantly distracted by the intermixed coding styles that are currently used. What do you think about adopting a consistent style and enforcing it automatically with RuboCop?

If so - let me know if you'd like something to be setup differently than in the default config.

**Comment by meh** [comment]
I used to be the janitor keeping the style consistent, but I usually do it once a year or something, and the time hasn't come yet, but we've had a surge of huge contributions, so that hasn't been done.

I'll check out RuboCop later tonight to see what the default config does.

**Comment by elia** [comment]
Hey @bbatsov I meant to reply when you asked the other day but waited to have the time for a thoughtful comment which of course never came 😖 sorry

@meh I'll post the config we kinda use at work to show my prefs. 

Anyway I don't like very much the idea of enforcing it (like failing the build or auto-correcting). I'd rather prefer to have it as a warning but I don't know how that can be achieved (eg. putting it into allowed failures means no one will pay attention)

Open to suggestions :)

**Comment by meh** [comment]
@elia yeah, I'd rather have warnings too.

**Comment by vais** [comment]
:+1: for automated quality control. For what it's worth, I'd be fine for it to fail the build - it should be run as part of `bundle exec rake` anyway (like JSHint does now). Making it optional kinda defeats the purpose :confused:

**Comment by elia** [comment]
The main difference as I see it is that Rubocop is more about code style than checking against possible pitfalls (where JSHint does the opposite).

As avdi pointed out in [his recent post](http://devblog.avdi.org/2015/07/08/ruby-is-defined-by-terrible-tools/):

>We have rudimentary warnings, but no way to granularly control which ones we see.

I think that would be great. 

Back on Rubocop maybe having the option to whitelist checks instead of patching the default config would be acceptable for failing a build. Still not sure tho.

@bbatsov do you know of any service that would comment on the PR with the results? (otherwise #freestartupidea :smile:) 
This way we could keep the results visible while not affecting the build status.


--- 

Btw the config I have in the current project is this:

```yml
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

Metrics/LineLength:
  Max: 180

Style/TrivialAccessors:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/AlignHash:
  Enabled: false
Style/TrailingComma:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
```

But it's far from complete in terms of checks I'd rather disable (e.g. `Use module_function instead of extend self.` or `Space inside parentheses detected.`)
